name: space
description: Space is a mental health journaling app for you! Our app is designed to help you make sense of your thoughts and emotions by enabling you to write journals according to your mood. With our intuitive interface and powerful AI-based algorithms, we make it easy for you to track your mental health over time and get insights into your emotional wellbeing. 


publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.1+2

environment:
  sdk: '>=2.18.6 <3.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  shared_preferences: ^2.0.15
  intl: ^0.17.0
  flutter_screenutil: ^5.6.0
  google_fonts: ^3.0.1
  path_provider: ^2.0.11
  table_calendar: ^3.0.8
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  local_auth: ^2.1.3
  flutter_local_notifications: ^13.0.0
  timezone: ^0.9.1
  flutter_slidable: ^2.0.0
  google_nav_bar: ^5.0.6
  flutter_svg: ^1.1.6
  flutter_native_splash: ^2.2.16
  easy_localization: ^3.0.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  
  change_app_package_name: ^1.1.0

  

flutter:
  uses-material-design: true

  assets:
    - assets/translations/
    - google_fonts/
    - assets/images/
    - assets/emojis/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Poppins
  #     fonts:
  #       - asset: assets/fonts/

  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

